version: '3.8'
services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ./database/oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.70.131
    oai-udr:
        container_name: "oai-udr"
        image: oaisoftwarealliance/oai-udr:develop
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - UDR_NAME=OAI_UDR
            - UDR_INTERFACE_NAME_FOR_NUDR=eth0
            - UDR_INTERFACE_PORT_FOR_NUDR=80
            - UDR_INTERFACE_HTTP2_PORT_FOR_NUDR=8080
            - UDR_API_VERSION=v1
            - MYSQL_IPV4_ADDRESS=192.168.70.131
            - MYSQL_USER=test
            - MYSQL_PASS=test
            - MYSQL_DB=oai_db
            - WAIT_MYSQL=120
            - USE_FQDN_DNS=yes
            - REGISTER_NRF=yes
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai-nrf
        depends_on:
            - mysql
            - oai-nrf
        networks:
            public_net:
                ipv4_address: 192.168.70.136
    oai-udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:develop
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - UDM_NAME=OAI_UDM
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - UDM_VERSION_NB=v1
            - USE_FQDN_DNS=yes
            - UDR_IP_ADDRESS=192.168.70.136
            - UDR_PORT=80
            - UDR_VERSION_NB=v1
            - UDR_FQDN=oai-udr
            - REGISTER_NRF=yes
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai-nrf
        depends_on:
            - oai-udr
        networks:
            public_net:
                ipv4_address: 192.168.70.137
    oai-ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:develop
        environment:
            - TZ=Europe/Paris
            - INSTANCE_ID=0
            - PID_DIR=/var/run
            - AUSF_NAME=OAI_AUSF
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - USE_FQDN_DNS=yes
            - UDM_IP_ADDRESS=192.168.70.137
            - UDM_PORT=80
            - UDM_VERSION_NB=v1
            - UDM_FQDN=oai-udm
            - REGISTER_NRF=yes
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai-nrf
        depends_on:
            - oai-udm
        networks:
            public_net:
                ipv4_address: 192.168.70.138
    oai-nrf:
        container_name: "oai-nrf"
        image: oaisoftwarealliance/oai-nrf:develop
        environment:
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            - NRF_INTERFACE_PORT_FOR_SBI=80
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - NRF_API_VERSION=v1
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
        networks:
            public_net:
                ipv4_address: 192.168.70.130
    oai-amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:develop
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0xa000
            - SST_0=222
            - SD_0=123
            - SST_1=128
            - SD_1=12
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=oai-smf
            - SMF_IPV4_ADDR_0=192.168.70.133
            - SMF_HTTP_VERSION_0=v1
            - SELECTED_0=true
            - SMF_INSTANCE_ID_1=2
            - SMF_FQDN_1=oai-smf
            - SMF_IPV4_ADDR_1=0.0.0.0
            - SMF_HTTP_VERSION_1=v1
            - SELECTED_1=false
            - MYSQL_SERVER=192.168.70.131
            - MYSQL_USER=root
            - MYSQL_PASS=linux
            - MYSQL_DB=oai_db
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - EXTERNAL_NRF=yes
            - NF_REGISTRATION=yes
            - SMF_SELECTION=yes
            - USE_FQDN_DNS=yes
            - EXTERNAL_AUSF=yes
            - EXTERNAL_UDM=no
            - EXTERNAL_NSSF=no
            - USE_HTTP2=no
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai-nrf
            - AUSF_IPV4_ADDRESS=192.168.70.138
            - AUSF_PORT=80
            - AUSF_API_VERSION=v1
            - AUSF_FQDN=oai-ausf
            - UDM_IPV4_ADDRESS=192.168.70.137
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=oai-udm
        depends_on:
            - mysql
            - vpp-upf-ulcl
            - vpp-upf-aupf1
            - vpp-upf-aupf2
            - oai-ext-dn-internet
            - oai-ext-dn-edge
            - oai-ausf
        networks:
            public_net:
                ipv4_address: 192.168.70.132
    oai-smf:
        container_name: "oai-smf"
        image: oaisoftwarealliance/oai-smf:develop
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.70.132
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - AMF_FQDN=oai-amf
            - UDM_IPV4_ADDRESS=192.168.70.137
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=oai-udm
            - UPF_IPV4_ADDRESS=192.168.70.201
            - UPF_FQDN_0=ulcl.node.5gcn.mnc95.mcc208.3gppnetwork.org
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - PCF_FQDN=oai-pcf
            - PCF_IPV4_ADDRESS=192.168.70.139
            - PCF_PORT=80
            - DEFAULT_CSCF_IPV4_ADDRESS=127.0.0.1  # only needed when ims is being used
            - USE_LOCAL_SUBSCRIPTION_INFO=yes  #Set to yes if SMF uses local subscription information instead of from an UDM
            - USE_LOCAL_PCC_RULES=no  #Set to yes if SMF uses local PCC rules instead of from a PCF
            - NRF_FQDN=oai-nrf
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - DISCOVER_PCF=no
            - USE_FQDN_DNS=no # Issue with PCF DNS resolving
            - ENABLE_USAGE_REPORTING=yes
            - DNN_NI0=oai
            - TYPE0=IPv4
            - DNN_RANGE0=12.1.1.151 - 12.1.1.253
            - NSSAI_SST0=1
            - NSSAI_SD0=0xFFFFFF
            - SESSION_AMBR_UL0=200Mbps
            - SESSION_AMBR_DL0=400Mbps
            - DNN_NI1=oai.ipv4
            - TYPE1=IPv4
            - DNN_RANGE1=12.1.1.51 - 12.1.1.150
            - NSSAI_SST1=1
            - NSSAI_SD1=1
            - SESSION_AMBR_UL1=100Mbps
            - SESSION_AMBR_DL1=200Mbps
            - DNN_NI2=default
            - TYPE2=IPv4
            - DNN_RANGE2=12.1.1.2 - 12.1.1.50
            - NSSAI_SST2=222
            - NSSAI_SD2=123
            - SESSION_AMBR_UL2=50Mbps
            - SESSION_AMBR_DL2=100Mbps
            - DNN_NI3=ims
            - TYPE3=IPv4v6
            - DNN_RANGE3=14.1.1.2 - 14.1.1.253
        extra_hosts:
            - "ulcl.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.70.201"
            - "aupf1.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.70.202"
            - "aupf2.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.70.203"
        depends_on:
            - oai-amf
            - oai-pcf
        networks:
            public_net:
                ipv4_address: 192.168.70.133
    oai-pcf:
        image: oaisoftwarealliance/oai-pcf:develop
        container_name: "oai-pcf"
        environment:
            - PCF_NAME=OAI-PCF
            - SBI_IF_NAME=eth0
            - SBI_PORT_HTTP1=80
            - SBI_PORT_HTTP2=9090
            - SBI_API_VERSION=v1
            - SBI_HTTP_VERSION=1
            - REGISTER_NRF=yes
            - CLIENT_HTTP_VERSION=1
            - NRF_HOST=oai-nrf
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - POLICY_DECISIONS_DIR=/openair-pcf/policies/policy_decisions
            - PCC_RULES_DIR=/openair-pcf/policies/pcc_rules
            - TRAFFIC_RULES_DIR=/openair-pcf/policies/traffic_rules
        volumes:
            - ./policies:/openair-pcf/policies
        depends_on:
            - oai-nrf
        networks:
            public_net:
                ipv4_address: 192.168.70.139
    vpp-upf-ulcl:
        image: oaisoftwarealliance/oai-upf-vpp:develop
        privileged: true
        container_name: "vpp-upf-ulcl"
        environment:
            - IF_1_IP=192.168.70.201
            - IF_1_TYPE=N4
            - IF_2_IP=192.168.72.201
            - IF_2_TYPE=N3
            - IF_2_NWI=access.5gcn.mnc95.mcc208.3gppnetwork.org
            - IF_2_DNAI=access
            - IF_3_IP=192.168.73.201
            - IF_3_TYPE=N9
            - IF_3_NWI=aupf1.node.5gcn.mnc95.mcc208.3gppnetwork.org
            - IF_3_DNAI=aupf1
            - IF_4_IP=192.168.74.201
            - IF_4_TYPE=N9
            - IF_4_NWI=aupf2.node.5gcn.mnc95.mcc208.3gppnetwork.org
            - IF_4_DNAI=aupf2
            - NAME=ULCL
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
#           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - SNSSAI_SD=123
            - SNSSAI_SST=222
            - DNN=default
            - REGISTER_NRF=yes
            - NRF_IP_ADDR=192.168.70.130
            - NRF_PORT=80
            - HTTP_VERSION=1
        depends_on:
            - oai-nrf
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.151
            public_net_access:
                ipv4_address: 192.168.72.151
            public_net_core11:
                ipv4_address: 192.168.73.151
            public_net_core21:
                ipv4_address: 192.168.74.151
    vpp-upf-aupf1:
        image: oaisoftwarealliance/oai-upf-vpp:develop
        privileged: true
        container_name: "vpp-upf-aupf1"
        environment:
            - IF_1_IP=192.168.70.202
            - IF_1_TYPE=N4
            - IF_2_IP=192.168.73.202
            - IF_2_TYPE=N9
            - IF_2_NWI=ulcl.node.5gcn.mnc95.mcc208.3gppnetwork.org
            - IF_2_DNAI=ulcl
            - IF_3_IP=192.168.75.202
            - IF_3_TYPE=N6
            - IF_3_NWI=internet.5gcn.mnc95.mcc208.3gppnetwork.org
            - IF_3_DNAI=internet
            - IF_3_IP_REMOTE=192.168.75.160 #ext-dn for NAT and routing
            - NAME=AUPF1
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=2
            - VPP_CORE_WORKER=3
            #           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - SNSSAI_SD=123
            - SNSSAI_SST=222
            - DNN=default
            - REGISTER_NRF=yes
            - NRF_IP_ADDR=192.168.70.130
            - NRF_PORT=80
            - HTTP_VERSION=1
        depends_on:
            - oai-nrf
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.152
            public_net_core11:
                ipv4_address: 192.168.73.152
            public_net_core12:
                ipv4_address: 192.168.75.152
    vpp-upf-aupf2:
        image: oaisoftwarealliance/oai-upf-vpp:develop
        privileged: true
        container_name: "vpp-upf-aupf2"
        environment:
            - IF_1_IP=192.168.70.203
            - IF_1_TYPE=N4
            - IF_2_IP=192.168.74.203
            - IF_2_TYPE=N9
            - IF_2_NWI=ulcl.node.5gcn.mnc95.mcc208.3gppnetwork.org
            - IF_2_DNAI=ulcl
            - IF_3_IP=192.168.76.203
            - IF_3_TYPE=N6
            - IF_3_NWI=edge.5gcn.mnc95.mcc208.3gppnetwork.org
            - IF_3_DNAI=edge
            - IF_3_IP_REMOTE=192.168.76.160 #ext-dn for NAT and routing
            - NAME=AUPF2
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=4
            - VPP_CORE_WORKER=5
            #           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - SNSSAI_SD=123
            - SNSSAI_SST=222
            - DNN=default
            - REGISTER_NRF=yes
            - NRF_IP_ADDR=192.168.70.130
            - NRF_PORT=80
            - HTTP_VERSION=1
        depends_on:
            - oai-nrf
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.153
            public_net_core21:
                ipv4_address: 192.168.74.153
            public_net_core22:
                ipv4_address: 192.168.76.153

    oai-ext-dn-internet:
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        privileged: true
        init: true
        container_name: "oai-ext-dn-internet"
        entrypoint: /bin/bash -c \
            "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
            "ip route add 12.1.1.0/24 via 192.168.75.202 dev eth0; ip route; sleep infinity"
        command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
        healthcheck:
            test: /bin/bash -c "iptables -L -t nat | grep MASQUERADE"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_core12:
                ipv4_address: 192.168.75.160
    oai-ext-dn-edge:
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        privileged: true
        init: true
        container_name: "oai-ext-dn-edge"
        entrypoint: /bin/bash -c \
            "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
            "ip route add 12.1.1.0/24 via 192.168.76.203 dev eth0; ip route; sleep infinity"
        command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
        healthcheck:
            test: /bin/bash -c "iptables -L -t nat | grep MASQUERADE"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_core22:
                ipv4_address: 192.168.76.160

networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
    public_net_core11:
        name: oai-public-core11
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core-11"

    public_net_core21:
        name: oai-public-core21
        ipam:
            config:
                - subnet: 192.168.74.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core-21"

    public_net_core12:
        name: oai-public-core12
        ipam:
            config:
                - subnet: 192.168.75.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core-12"

    public_net_core22:
        name: oai-public-core22
        ipam:
            config:
                - subnet: 192.168.76.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core-22"
